#!/system/bin/sh
#############################
local_dir="/data/local"
eval "$(cat "$local_dir/Unpacker_lang/$(cat "$local_dir/Unpacker_lang/selection.txt").lang")"
#############################
out_extract_key=$local_dir/UnpackerSystem/extract_keys
busybox mkdir "$out_extract_key" 2>/dev/null

if busybox test -s "$file"; then
    check_alg="$(avbtool info_image --image "$file" 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
    if [ "$check_alg" != "NONE" -a ! -z "$check_alg" ]; then
        echo
        echo ".....Algorithm: $check_alg"
        f_name="$(echo "$file" | busybox awk -F"." '{ print $1 }')"
        offset_avb="$(python39 $local_dir/binary/bin_system/find_avb0.py "$file" "41564230" | busybox head -1)"
          if [ "$offset_avb" != "None" ]; then
            size_magic="$(avbtool info_image --image "$file" | busybox awk '/Header Block:/ { print $3 }')"
            size_ayten="$(avbtool info_image --image "$file" | busybox awk '/Authentication Block:/ { print $3 }')"
            xxx="$(busybox expr "$offset_avb" \+ 64)"
            offset_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
            xxx="$(busybox expr "$offset_avb" \+ 72)"
            size_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
            real_offset_key="$(busybox expr "$offset_avb" \+ "$size_magic" \+ "$size_ayten" \+ "$offset_key")"
            of_hex="$(printf "%x\n" "$real_offset_key")"
            xxd -ps -s 0x"$of_hex" -l "$size_key" "$file" | xxd -r -ps >"$out_extract_key"/"$f_name"_pubkey.pem
            if [ $(echo $?) -eq 0 -a -s "$out_extract_key"/"$f_name"_pubkey.pem ]; then
                echo
                echo ".....$key_successfully_extracted!"
                echo ".....$saved: "$out_extract_key"/"$f_name"_pubkey.pem"
                sha_sum="$(busybox sha1sum "$out_extract_key"/"$f_name"_pubkey.pem | busybox awk '{ print $1 }')"
                echo ".....sha1:  $sha_sum"
                echo
            else
                echo ".....$key_extraction_error!"
                echo
            fi
        else
            echo
            echo ".....$error_not_found offset AVB0"
            echo
        fi
    else
        echo
        echo ".....$file /$nd/$file $not_signed!"
        echo
    fi
else
    echo
    echo ".....$no_file_to_process!"
    echo
fi

unset xxx
