#!/system/bin/sh

myk() {
    read b
    if [ "$b" -le "7" ]; then
        echo ".....$convert_to "$file".br...$waiting..."
        brotli -"$b"f ./"$file"
        echo
    else
        echo
        echo ".....$enter_number $from 0 $to1 7:"
        myk
        echo
    fi
    if [ $(echo $?) -eq 0 ]; then
 #echo
        echo ".....$conversion_completed_successfully!"
        echo
    else
 #echo
        echo ".....$convert_error."
        echo
    fi
}

if [ -f ./"$file" ]; then
    echo
    echo ".....$enter_compression_ratio_0_7:"
    myk
else
    echo
    echo ".....$in_folder_no "$file"."
    echo
fi
