#!/system/bin/sh

size_output_raw() {
    if busybox test -s "$file"; then
        size_out="$(busybox stat -c %s "$file")"
        size_free="$(busybox expr "$(tune2fs -l "$file" | busybox awk '/Free blocks:/ { print $3 }')" \* 4096 / 1024 / 1024)"
        echo ".....$size1 raw == $size_out $byte"
        echo ".....$free_space: $size_free mb"
        echo
    fi
    return
}
#r_name=$(echo $file | busybox sed 's!.*\/!!' | busybox awk -F"-|_|[+]|[.]|[{]|[(]" '{ print $1 }')

r="$(busybox basename $file)"
r_name=${r%.*}

if [ -f ./"$file" ]; then
    if [ -z "$(busybox hexdump -C -n 4 ./"$file" | grep '3a ff 26 ed')" ]; then
        echo
        echo ".....$converting..."
        echo
        img2simg ./"$file" ./"$r_name".sparse.img 2>/dev/nul
        if [ $(echo $?) -eq 0 ]; then
            echo
            echo ".....$received_image sparse: \""$r_name".sparse.img\"!"
            size_output_raw
            echo
        else
            echo
            echo ".....$convert_error!"
            echo
        fi
    else
        echo
        echo ".....$image_is_already sparse."
        echo
    fi
else
    echo
    echo ".....$no_image_in_folder "$file"."
    echo
fi
