#!/system/bin/sh

dir_bb="$binary_dir/lib"
dir_loop="$local_dir/$a"

if [ -z "$("$dir_bb"/busybox mount | "$dir_bb"/busybox cut -d" " -f3 | "$dir_bb"/busybox grep "$dir_loop$")" ]; then

   mkdir "$dir_loop" 2>/dev/null
   "$dir_bb"/busybox mount -t ext4 -o rw,loop "$file" "$dir_loop" 2>/dev/null
   if [ "$?" -eq "0" ]; then
      echo
      echo "     $file $mount_in_folder: $dir_loop"
      echo
   else
      loop="$("$dir_bb"/busybox losetup -f)"
      i="$(echo "$loop" | busybox awk -F"loop" '{ print $2 }')"
      [ -e /dev/block/loop1 ] && minor=$(busybox ls -l /dev/block/loop1 | busybox awk '{ print $6 }')
      "$dir_bb"/busybox mknod $loop b 7 $(($i * $minor)) 2>/dev/null
      "$dir_bb"/busybox losetup $loop "$a".img 2>/dev/null
      "$dir_bb"/busybox mount -t ext4 -o loop,noatime $loop "$dir_loop"

      if [ "$?" -eq "0" ]; then
         echo
         echo "     $file $mount_in_folder: $dir_loop"
         echo
      else
         echo
         echo ".....$mount_error"
         echo
         "$dir_bb"/busybox losetup -d $loop
      fi
   fi
else
   echo
   echo ".....$folder_already_mounted $dir_loop"
   echo
fi
