#!/system/bin/sh

#loop=$(busybox mount | grep "$file" | cut -d" " -f1)

loop=$(busybox mount | cut -d" " -f1,3 | grep "$file$" | cut -d" " -f1)
loop_d=$(busybox mount | cut -d" " -f3 | grep "$file$")
echo
echo ".....$unmounting $file..."
echo
if [ ! -z "$loop_d" ]; then


 pid_term="$(cat /proc/$$/status | busybox awk '/^PPid:/ { print $2 }')"
    fuser -vm "$loop_d" &>$binary_dir/fuser.txt
 
    check_pid="$(busybox cat $binary_dir/fuser.txt | busybox grep -o "$pid_term")"
 if [ -z "$check_pid" ]; then

 fuser -skm "$loop_d"
 busybox umount "$loop_d"
if [ "$?" -eq 0 ]; then
losetup -d "$loop" 2> /dev/null
busybox rm -rf "$loop_d"
            echo ".....$successfully_unmounted: $loop_d"
echo
else
echo
            echo ".....$unmount_error!"
fi
else
echo
        echo ".....$unmount_error!"
echo
#echo ".....Сначала выйдите в терминале из папки: $loop_d"
        echo ".....$shut_down_uka"
echo
fi
else
echo
    echo ".....$folder_not_mounted!"
echo
fi

busybox rm -f $binary_dir/fuser.txt
