#!/system/bin/sh

clear
pack_d="$pack_d"
. $binary_dir/pack_img

my_br() {
    myk() {
        read n
        if busybox test "$(busybox expr "$n" \* 1 2>/dev/null)"; then
            n="$n"
        else
            echo
        echo ".....$compression_ratio_not_entered"
        echo ".....$by_default: 0"
            echo
            n="0"
        fi
        if busybox test "$n" -le "7"; then
            echo
        echo ".....$convert_to "$pack_d".new.dat.br"
        echo ".....$compression_ratio: $n"
        echo ".....$waiting..."
            brotli -"$n"f "$outdir"/"$pack_d".new.dat
            echo
        else
            echo
        echo ".....$enter_number $from 0 $to1 7:"
            myk
            echo
        fi
        if [ $(echo $?) -eq 0 ]; then
        echo ".....$deliting "$pack_d".new.dat"
            rm -f "$outdir"/"$pack_d".new.dat
            echo
        echo ".....$conversion_completed_successfully!"
            echo
        #echo ".....$size1 raw == $size_out $byte"
        #echo ".....$free_space: $size_free mb"
            echo -e "\033[33;1m.....$size1 raw == $size_out $byte\033[0m"
            echo -e "\033[33;1m.....$free_space: $size_free mb\033[0m"
            echo
        else
            echo
        echo ".....$convert_error!"
            echo
        fi
    }

    if busybox test -s "$outdir"/"$pack_d".new.dat; then
        echo
        echo ".....$to_convert_to "$pack_d".new.dat.br $enter_compression_ratio_0_7:"
        myk
    else
        echo
        echo ".....$in_folder_no "$pack_d".new.dat"
        echo
    fi
}

#----------------------------finish pack

if busybox test -s "$outdir"/"$pack_d".new.img; then

    mv_br() {
        busybox test -s "$outdir"/"$pack_d".new.new.dat && busybox mv -f "$outdir"/"$pack_d".new.new.dat "$outdir"/"$pack_d".new.dat
        busybox test -f "$outdir"/"$pack_d".new.patch.dat && busybox mv -f "$outdir"/"$pack_d".new.patch.dat "$outdir"/"$pack_d".patch.dat
        busybox test -s "$outdir"/"$pack_d".new.transfer.list && busybox mv -f "$outdir"/"$pack_d".new.transfer.list "$outdir"/"$pack_d".transfer.list
    }

    b="python31 $binary_dir/bin_system/img2sdat-master/img2sdat.py "$outdir"/"$pack_d".new.img $outdir"
    if [ -d ./"$pack_d" ]; then
        a=$(busybox awk -F"=" '/ro.build.version.release=/ { print $2 }' "$pack_d"/build.prop 2>/dev/null) || a=$(busybox awk -F"=" '/ro.build.version.release=/ { print $2 }' "$pack_d"/"$pack_d"/build.prop 2>/dev/null)

        g=$(busybox grep 'ro.build.version.sdk=.*.' $local_dir/UnpackerSystem/"$pack_d"/build.prop | busybox grep -Eo '.{2}$') 2>/dev/null || g=$(busybox grep 'ro.build.version.sdk=.*.' "$pack_d"/"$pack_d"/build.prop | busybox grep -Eo '.{2}$') 2>/dev/null
        if [ "$g" -ge "24" ]; then
            echo
            echo "......$version_found API = $g $android_version: $a"
            echo
            echo "......$convert_to .dat..."
            echo
            $b 4
            if [ $(echo $?) -eq 0 ]; then
                mv_br
                echo
                echo ".....$complete"
                echo
                echo ".....$deliting "$pack_d".new.img..."
                rm -f "$outdir"/"$pack_d".new.img
                echo
                my_br
            else
                echo
                echo ".....$convert_error!"
                echo
            fi

        elif [ "$g" -eq "21" ]; then
            echo
            echo "......$version_found API = $g $android_version: $a"
            echo
            echo "......$convert_to .dat..."
            echo
            $b 1
            if [ $(echo $?) -eq 0 ]; then
                mv_br
                echo
                echo ".....$complete"
                echo
                echo ".....$deliting "$pack_d".new.img..."
                rm -f "$outdir"/"$pack_d".new.img
                echo
                my_br
            else
                echo
                echo ".....$convert_error!"
                echo
            fi

        elif [ "$g" -eq "22" ]; then
            echo
            echo "......$version_found API = $g $android_version: $a"
            echo
            echo "......$convert_to .dat..."
            echo
            $b 2
            if [ $(echo $?) -eq 0 ]; then
                mv_br
                echo
                echo ".....$complete"
                echo
                echo ".....$deliting "$pack_d".new.img..."
                rm -f "$outdir"/"$pack_d".new.img
                echo
                my_br
            else
                echo
                echo ".....$convert_error!"
                echo
            fi

        elif [ "$g" -eq "23" ]; then
            echo
            echo "......$version_found API = $g $android_version: $a"
            echo
            echo "......$convert_to .dat..."
            echo
            $b 3
            if [ $(echo $?) -eq 0 ]; then
                mv_br
                echo
                echo ".....$complete"
                echo
                echo ".....$deliting "$pack_d".new.img..."
                rm -f "$outdir"/"$pack_d".new.img
                echo
                my_br
            else
                echo
                echo ".....$convert_error!"
                echo
            fi

        else
            echo ".....$version_not_found SDK."
            echo
            echo ".....$enter_number_version_android_for_built:"
            echo
            $b
            if [ $(echo $?) -eq 0 ]; then
                mv_br
                echo
                echo ".....$complete"
                echo
                echo ".....$deliting "$pack_d".new.img..."
                rm -f "$outdir"/"$pack_d".new.img
                echo
                my_br
            else
                echo
                echo ".....$convert_error!"
                echo
            fi
        fi
    fi
else
    echo ".....$no_image \""$pack_d".new.img\" $for_conversion"
fi
rm -f $local_dir/python31/tmp* tmp*
