#!/system/bin/sh
#############################
local_dir="/data/local"
eval "$(cat "$local_dir/Unpacker_lang/$(cat "$local_dir/Unpacker_lang/selection.txt").lang")"
#############################
clear
pack_d="$pack_d"

. $local_dir/binary/pack_img

mv_dat() {
    busybox test -s "$outdir"/"$pack_d".new.new.dat && busybox mv -f "$outdir"/"$pack_d".new.new.dat "$outdir"/"$pack_d".new.dat
    busybox test -f "$outdir"/"$pack_d".new.patch.dat && busybox mv -f "$outdir"/"$pack_d".new.patch.dat "$outdir"/"$pack_d".patch.dat
    busybox test -s "$outdir"/"$pack_d".new.transfer.list && busybox mv -f "$outdir"/"$pack_d".new.transfer.list "$outdir"/"$pack_d".transfer.list
}

if busybox test -s "$outdir"/"$pack_d".new.img; then

    b="python39 $local_dir/binary/bin_system/img2sdat-master/img2sdat5.py "$outdir"/"$pack_d".new.img $outdir"
    if [ -d ./"$pack_d" ]; then
        a=$(busybox awk -F"=" '/ro.build.version.release=/ { print $2 }' "$pack_d"/build.prop 2>/dev/null) || a=$(busybox awk -F"=" '/ro.build.version.release=/ { print $2 }' "$pack_d"/system/build.prop 2>/dev/null)
        g=$(busybox grep 'ro.build.version.sdk=.*.' $local_dir/UnpackerSystem/"$pack_d"/build.prop | busybox grep -Eo '.{2}$') 2>/dev/null || g=$(busybox grep 'ro.build.version.sdk=.*.' "$pack_d"/system/build.prop | busybox grep -Eo '.{2}$') 2>/dev/null
        if [ "$g" -ge "24" ]; then
            echo
            echo "......$version_found АРI = $g $android_version: $a"
            echo
            echo "......$convert_to .dat..."
            echo
            $b 4
            if [ $(echo $?) -eq 0 ]; then
                mv_dat
                echo
                echo ".....$complete"
                echo
                echo ".....$size1 raw == $size_out $byte"
                echo ".....$free_space: $size_free mb"
                echo
                rm -f "$outdir"/"$pack_d".new.img
            else
                echo
                echo ".....$convert_error!"
                echo
            fi

        elif [ "$g" -eq "21" ]; then
            echo
            echo "......$version_found АРI = $g $android_version: $a"
            echo
            echo "......$convert_to .dat..."
            echo
            $b 1
            if [ $(echo $?) -eq 0 ]; then
                mv_dat
                echo
                echo ".....$complete"
                echo
                echo ".....$size1 raw == $size_out $byte"
                echo ".....$free_space: $size_free mb"
                echo
                rm -f "$outdir"/"$pack_d".new.img
            else
                echo
                echo ".....$convert_error!"
                echo
            fi

        elif [ "$g" -eq "22" ]; then
            echo
            echo "......$version_found АРI = $g $android_version: $a"
            echo
            echo "......$convert_to .dat..."
            echo
            $b 2
            if [ $(echo $?) -eq 0 ]; then
                mv_dat
                echo
                echo ".....$complete"
                echo
                echo ".....$size1 raw == $size_out $byte"
                echo ".....$free_space: $size_free mb"
                echo
                rm -f "$outdir"/"$pack_d".new.img
            else
                echo
                echo ".....$convert_error!"
                echo
            fi

        elif [ "$g" -eq "23" ]; then
            echo
            echo "......$version_found АРI = $g $android_version: $a"
            echo
            echo "......$convert_to .dat..."
            echo
            $b 3
            if [ $(echo $?) -eq 0 ]; then
                mv_dat
                echo
                echo ".....$complete"
                echo
                echo ".....$size1 raw == $size_out $byte"
                echo ".....$free_space: $size_free mb"
                echo
                rm -f "$outdir"/"$pack_d".new.img
            else
                echo
                echo ".....$convert_error!"
                echo
            fi

        else
            echo ".....$version_not_found SDK."
            echo
            echo ".....$enter_number_version_android_for_built:"
            echo
            $b
            if [ $(echo $?) -eq 0 ]; then
                mv_dat # функция переименования
                echo
                echo ".....$complete"
                echo
                echo ".....$size1 raw == $size_out $byte"
                echo ".....$free_space: $size_free mb"
                echo
                rm -f "$outdir"/"$pack_d".new.img
            else
                echo
                echo ".....$convert_error!"
                echo
            fi
        fi
    fi
else
    echo ".....$no_image \""$pack_d".new.img\" $for_conversion"
fi
rm -f $local_dir/python39/tmp* tmp*
