#!/system/bin/sh

 clear
#cd /data/local/UnpackerSystem

 t="$pack_d"
 config="config/${pack_d}"

 echo
 echo ".....Проверка ${pack_d}_fs_config..."


 find "$pack_d" -type d -exec busybox stat -c '%N %u %g %a' {} \; | busybox sed 's!$! _d!' > $config/"$pack_d"_ff.txt
 find "$pack_d" -type f -exec busybox stat -c '%N %u %g %a' {} \; | busybox sed 's!$! _f!' >> $config/"$pack_d"_ff.txt
 find "$pack_d" -type l -exec busybox stat -c '%N %u %g %a' {} \; | busybox sed 's!$! _l!' | busybox sed -e s!\'!!g >> $config/"$pack_d"_ff.txt

if busybox test -s "$config"/"$pack_d"_ff.txt -a -s "$config"/"$pack_d"_avto_f.txt; then
    #clear
 busybox diff -s "$config"/"$pack_d"_avto_f.txt "$config"/"$pack_d"_ff.txt | busybox grep -E "\+$t" | busybox sed 's!+!!' | busybox grep '_d$' > "$config"/"$pack_d"_avto_fff.txt
 busybox diff -s "$config"/"$pack_d"_avto_f.txt "$config"/"$pack_d"_ff.txt | busybox grep -E "\+$t" | busybox sed 's!+!!' | busybox grep '_f$' >> "$config"/"$pack_d"_avto_fff.txt
busybox diff -s "$config"/"$pack_d"_avto_f.txt "$config"/"$pack_d"_ff.txt | busybox grep -E "\+$t" | busybox sed 's!+!!' | busybox grep '_l$' >> "$config"/"$pack_d"_avto_fff.txt

 busybox cat "$config"/"$pack_d"_avto_f.txt | busybox awk '{ print $1 }' | busybox sort > "$config"/"$pack_d"_avto_yy_f.txt
busybox cat "$config"/"$pack_d"_fs_config | busybox awk '{ print $1 }' | busybox sort > "$config"/"$pack_d"_avto_ss_f.txt


busybox diff -s "$config"/"$pack_d"_avto_ss_f.txt "$config"/"$pack_d"_avto_yy_f.txt | busybox grep -E "\+$t" | busybox grep -v "\+$t$" | busybox sed 's!^+!!' | while read ee; do
busybox cat "$config"/"$pack_d"_avto_f.txt | busybox grep "$ee " >> "$config"/"$pack_d"_avto_fff.txt
done
fi

if busybox test -s "$config"/"$pack_d"_avto_fff.txt; then

 busybox cat "$config"/"$pack_d"_avto_fff.txt | while read a; do


 fun_f()
{

 if [ "$pack_d" == "$n" -a "$vin" != "_l$" ]; then
 name_f="$(busybox cat "$config"/"$pack_d"_avto_f.txt | busybox awk -F"/" '{ print $1"/"$2 }' | busybox grep "$vin")"
if [ -z "$name_f" ]; then
 name_f="$(busybox grep "$n" "$config"/"$pack_d"_avto_f.txt | busybox grep "$vin")"
 fi
else
 name_f="$(busybox grep "$n" "$config"/"$pack_d"_avto_f.txt | busybox grep "$vin")"
fi

if [ "$vin" == "_l$" ]; then
 if [ -L "$a1" ]; then

 #name_f="$(busybox grep "$pack_d" "$config"/"$pack_d"_avto_f.txt | busybox grep "$vin")"

 link="$(busybox stat -c "%N" "$a1" 2> /dev/null | busybox awk '{ print $3 }' | busybox sed 's!'$PWD'!!' | busybox sed -e s!\'!!g)"
 perm_f="0 0 777 $link"

 #if [ ! -z "$name_f" ]; then
 
 #perm_f="$(echo "$name_f" | busybox awk '{ print $4" "$5" "$6" "$3 }' | busybox sort | busybox uniq -c | busybox sort -nk1 | busybox awk -v m="$link" '{ print $2" "$3" "$4" "m }' | busybox tail -1)"
 #else
 #perm_f="0 0 777 $link"
 #echo > /dev/null
 #fi
fi
 else
 perm_f="$(echo "$name_f" | busybox awk '{ print $2" "$3" "$4 }' | busybox sort | busybox uniq -c | busybox sort -nk1 | busybox awk '{ print $2" "$3" "$4 }' | busybox tail -1)"
 fi

 if [ ! -z "$perm_f" ]; then

 name_a="$(echo "$a1" | busybox awk '{ print $1 }')"
 
 real_name="$(echo "$name_a" "$perm_f")"
#echo "$name_a" "$perm_f" >> "$config"/"$pack_d"_fs_config.tmp
#echo "$real_name" | busybox awk -v a="$perm_f" '{if(NF < 4) {next}} {if(NF = "4") {print $1" "a}}'>> "$config"/"$pack_d"_fs_config.tmp


echo "$real_name" | busybox awk -v a="$perm_f" '{if(NF < 4) {next}} {if(NF == 4) {print $1" "a}} {if(NF == 5) {print $1" "a}}' >> "$config"/"$pack_d"_fs_config.tmp

fi
return
}

a1="$(echo "$a" | busybox awk '{ print $1 }')"
n="$(echo "${a1%/*}")"
e="$(echo "${n%/*}")"
d="$(echo "${e%/*}")"
c="$(echo "${d%/*}")"
g="$(echo "${c%/*}")"
f="$(echo "${g%/*}")"
u="$(echo "${f%/*}")"

 
[ ! -z "$(echo "$a" | busybox grep "_d$")" ] && vin="_d$"
[ ! -z "$(echo "$a" | busybox grep "_f$")" ] && vin="_f$"
[ ! -z "$(echo "$a" | busybox grep "_l$")" ] && vin="_l$"


 if [ -z "$(busybox grep '$a1 ' "$config"/"$pack_d"_fs_config)" ]; then

 for tt in "$n" "$e" "$d" "$c" "$g" "$f" "$u"; do
if [ ! -z "$(busybox grep "$tt" "$config"/"$pack_d"_avto_f.txt | busybox awk '{ print $1 }')" ]; then
 if [ ! -z "$(busybox grep "$tt" "$config"/"$pack_d"_avto_f.txt | busybox grep "$vin")" ]; then
n="$tt"
 fun_f
break
 else
 n="$(echo "${tt%/*}")"
 fun_f
 break
 fi
fi
done


fi
done
fi


 if busybox test -s "$config"/"$pack_d"_fs_config.tmp; then
busybox cat "$config"/"$pack_d"_fs_config.tmp >> "$config"/"$pack_d"_fs_config
busybox rm -f "$config"/"$pack_d"_fs_config.tmp
fi

busybox sed -i '/^$/d' "$config"/"$pack_d"_fs_config
 busybox awk '!($0 in a) {a[$0];print}' "$config"/"$pack_d"_fs_config > "$config"/"$pack_d"_conf.tmp && busybox mv -f "$config"/"$pack_d"_conf.tmp "$config"/"$pack_d"_fs_config

 
 clear