#!/system/bin/sh

#clear
file="$1"
file_key="$2"

if busybox test -s "$file"; then
  unset check_alg
  check_alg="$(avbtool info_image --image "$file" 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"

  if busybox test "$check_alg" != "NONE" -a ! -z "$check_alg"; then

    #f_name="$(echo "$file" | busybox awk -F"." '{ print $1 }')"
    r="$(busybox basename $file)"

    f_name=${r%.*}

        offset_avb="$(python39 $binary_dir/bin_system/find_avb0.py "$file" "41564230" | busybox head -1)"

    if busybox test "$offset_avb" != "None"; then

      size_magic="$(avbtool info_image --image "$file" | busybox awk '/Header Block:/ { print $3 }')"

      size_ayten="$(avbtool info_image --image "$file" | busybox awk '/Authentication Block:/ { print $3 }')"

      xxx="$(busybox expr "$offset_avb" \+ 64)"
      offset_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"

      xxx="$(busybox expr "$offset_avb" \+ 72)"

      size_key="$(busybox printf "%d\n" $(busybox hexdump -C -s "$xxx" -n 8 "$file" | busybox awk 'NR==1 { print "0x"$2$3$4$5$6$7$8$9 }'))"
      size_new_key="$(busybox stat -c %s "$file_key")"
      real_offset_key_dec="$(busybox expr "$offset_avb" \+ "$size_magic" \+ "$size_ayten" \+ "$offset_key")"

      real_offset_key="$(printf "%x\n" "$real_offset_key_dec")"

      real_size_key="$(busybox expr "$real_offset_key_dec" \+ "$size_key")"

      if busybox test "$size_key" == "$size_new_key"; then

        sha11="$(avbtool info_image --image "$file" | busybox awk '/^Public key \(sha1\):/ { print $4}')"

        bin_writekey "$file" "$real_offset_key" "$file_key"

        if [ $(echo $?) -eq 0 ]; then
          check_new_alg="$(avbtool info_image --image "$file" 2>/dev/null | busybox awk '/^Algorithm:/ { print $2 }')"

          sha12="$(avbtool info_image --image "$file" | busybox awk '/^Public key \(sha1\):/ { print $4}')"

          if [ ! -z "$sha11" -a ! -z "$sha12" ]; then
            echo
            echo ".....Algorithm: $check_new_alg"
            echo ".....sha1 public key: $sha12"
            echo
          else
                    echo ".....$error_change_key!"
            echo
          fi
        else
		 echo ".....$error_change_key!"
          echo
        fi
      else
        echo
        echo ".....$error_key_sizes_do_not_match"
        echo
      fi
    else
      echo
            echo ".....$error_not_found offset AVB0"
      echo
    fi
  else
    echo
        echo ".....$f_i_l_e $nd/$file $not_signed!"
    echo
  fi
else
  echo
    echo ".....$no_file_to_process!"
  echo
fi
unset xxx
