#!/system/bin/sh

#dat_name=$(echo $file | busybox sed 's!.*\/!!' | busybox awk -F"-|_|[+]|[.]|[{]|[(]" '{ print $1 }')

#r="$(busybox basename $file)"
#dat_name=${r%.*}

dat_name=$(echo $file | busybox sed 's!.*\/!!' | busybox awk -F".new.dat" '{ print $1 }')

if busybox test -s ./"$dat_name".transfer.list; then
  echo
  echo ".....$converting $file..."
  echo
  sdat2img "$dat_name".transfer.list "$dat_name".new.dat /"$ndd"/"$dat_name".img
  if [ $(echo $?) -eq 0 ]; then
    file=/"$ndd"/"$dat_name".img
    nd="$ndd"
    . $binary_dir/unpack_img
  else
    echo
    echo ".....$convert_error $file"
    echo
  fi
else
  echo
  echo ".....$file_not_found "$dat_name".transfer.list."
fi
