#!/system/bin/sh
#############################
local_dir="/data/local"
eval "$(cat "$local_dir/Unpacker_lang/$(cat "$local_dir/Unpacker_lang/selection.txt").lang")"
#############################

br_name=$(echo $file | busybox sed 's!.*\/!!' | busybox awk -F".new.dat.br" '{ print $1 }')

if [ -f ./"$br_name".transfer.list ]; then
    echo
    echo ".....$converting "$br_name".new.dat.br..."
    brotli -df "$br_name".new.dat.br -o "$br_name".new.dat 2>/dev/null

    if [ $(echo $?) -eq 0 ]; then
        echo
        echo ".....$converting "$br_name".new.dat..."
        echo
        sdat2img "$br_name".transfer.list "$br_name".new.dat "$br_name".img
        if [ $(echo $?) -eq 0 ]; then
            echo
            echo ".....$deliting "$br_name".new.dat..."
            rm -f $PWD/"$br_name".new.dat
            file=/"$nb"/"$br_name".img
            nd="$nb"
            . $local_dir/binary/unpack_img
        else
            echo
            echo ".....$convert_error "$br_name".new.dat"
            echo
        fi
    else
        echo
        echo ".....$convert_error "$br_name".new.dat.br"
        echo
    fi
else
    echo
    echo ".....$file_not_found "$br_name".transfer.list."
fi
